[package]
name = "any"
version = "0.1.0"
authors = ["WG-zhangfeng <d177178179feng>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
