[package]
name = "any"
version = "0.1.0"
authors = ["WG-zhangfeng <d177178179feng>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#url = "2.2.0"
percent-encoding = "2.1.0"
bytes = "0.6.0"